# Site settings
title: Le Anh Tien
email: tienla.ict@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: 
github_username:
facebook_username: tienla.ict
# Build settings
markdown: kramdown
